const roleList = {
  independant: [
    {
      roleName: 'Tanner',
      id: '1',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Easy',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: 'You hate your job and want to die.',
    },
    {
      roleName: 'Auracabra',
      id: '2',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Hunt for anyone with an aura. If none left hunt everyone.',
    },
    {
      roleName: 'Cult Leader',
      id: '3',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Induct a new player each night until everyone is in your cult.',
    },
    {
      roleName: 'Hoodlum',
      id: '4',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: 'Choose two players and outlive them.',
    },
    {
      roleName: 'Illuminati',
      id: '5',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'You know everyone’s role and just need to live to the end.',
    },
    {
      roleName: 'Lone Wolf',
      id: '6',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Wake with the Werewolves and hunt villagers but win alone.',
    },
    {
      roleName: 'Necromancer (alt)',
      id: '7',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Predict one player to die and cause another player to die.',
    },
    {
      roleName: 'Vampire',
      id: '8',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: '',
    },
    {
      roleName: 'Chupacabra',
      id: '9',
      roleType: 'independant',
      set: 'Extreme',
      infoValue: '2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: 'Hunt for Werewolves. If none left hunt everyone',
    },
  ],
  teamSwitcher: [
    {
      roleName: 'Black Cat',
      id: '10',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'The team that kills you loses their most valuable player.',
    },
    {
      roleName: 'Bloody Marianne (Grim Reaper)',
      id: '11',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'The team that kills you becomes your enemy. Seek revenge and kill every night from beyond the grave.',
    },
    {
      roleName: 'Blighted',
      id: '12',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'If bitten by a Werewolf you turn into a Werewolf',
    },
    {
      roleName: 'Copycat ( new Doppelganger)',
      id: '13',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Join the team of another player and take on their role when they die.',
    },
    {
      roleName: 'Flipper ',
      id: '14',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: '',
    },
    {
      roleName: 'Grave Robber',
      id: '15',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'When you should die steal the identity of another player who will die in your place.',
    },
    {
      roleName: 'Nostradamus (alt)',
      id: '16',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Predict which team will win and join that team. You can change your mind but it will cost your life.',
    },
    {
      roleName: 'Professor Impatience',
      id: '17',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'If you are eliminated players eliminate two players each day and wolves eliminate two players each night for the rest of the game.',
    },
    {
      roleName: 'Time Bandit',
      id: '18',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Steal time from team that kills you: One minute days for Villagers or 5 Seconds to kill for Werewolves.',
    },
    {
      roleName: 'Investigator ',
      id: '19',
      roleType: 'teamSwitcher',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'if you can find a wolf win with the Villagers if not you help them stay hidden and win with the Werewolves',
    },
  ],
  specialVillager: [
    {
      roleName: 'Eye of the Seer',
      id: '20',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'When you die the Seer sees everyone as a Villager.',
    },
    {
      roleName: 'Oracle',
      id: '21',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: "Once per game learn one player's exact role",
    },
    {
      roleName: 'Outcast',
      id: '22',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'If you die Village celebrates!',
    },
    {
      roleName: 'Cupid',
      id: '23',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Choose two players to fall in love. If one dies the other dies of heartbreak.',
    },
    {
      roleName: 'Cutthroat',
      id: '24',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: 'You may kill a neighbor during the day',
    },
    {
      roleName: 'Hunter',
      id: '25',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You carry a gun. When you die you may kill another player.',
    },
    {
      roleName: 'Huntress',
      id: '26',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You have a gun and one bullet. You may shoot another player at night.',
    },
    {
      roleName: 'Innocent',
      id: '27',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'If you die the next day the village must keep killing players until they kill a Werewolf.',
    },
    {
      roleName: 'Influencer (Rabble Rouser)',
      id: '28',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'One extra vote for death while alive for life when you are dead',
    },
    {
      roleName: 'Magistrate (new Prince)',
      id: '29',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'You can veto the decision of one trial per game',
    },
    {
      roleName: 'Mayor',
      id: '30',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Your vote counts twice',
    },
    {
      roleName: 'Revealer',
      id: '31',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You may gamble that you can find a Werewolf. If you are right they die. If you are wrong you die.',
    },
    {
      roleName: 'Robber (Hackmaster/Dr. Helgo)',
      id: '32',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Trade cards with another player.',
    },
    {
      roleName: 'Spellcaster (alt)',
      id: '33',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Everynight silence a player who can not speak nominate or vote the next day',
    },
    {
      roleName: 'The Thing',
      id: '34',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Tap a neighbor at night and they will know you are a villager.',
    },
    {
      roleName: 'Tough Guy (alt)',
      id: '35',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Slower',
      moderatorText: 'If attacked at night you don’t die right away.',
    },
    {
      roleName: 'Aura Seer',
      id: '36',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Learn if players have a role with a plain or special aura.',
    },
    {
      roleName: 'Beholder',
      id: '37',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'You know who is the Seer',
    },
    {
      roleName: 'Bodyguard',
      id: '38',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '1',
      gameSpeed: 'Slower',
      moderatorText: 'Protect players from being killed at night',
    },
    {
      roleName: 'Exposer (alt)',
      id: '39',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Wake every night. One night per game you may target a player. The next day that player’s role is exposed.',
    },
    {
      roleName: 'Insomniac (alt)',
      id: '40',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Learn if one of your neighbors was awake in the night.',
    },
    {
      roleName: 'Mad Bomber',
      id: '41',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You have a bomb. When you die you will kill your neighbors to the right or left.',
    },
    {
      roleName: 'Soothsayer (Apprentice Mentalist)',
      id: '42',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Learn if two players are on the same team or not',
    },
    {
      roleName: 'Priest',
      id: '43',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '1',
      gameSpeed: 'Slower',
      moderatorText: 'Bless a player to give them an extra life.',
    },
    {
      roleName: 'Reactive Seer',
      id: '44',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Search for Werewolves at night after each villager is lynched',
    },
    {
      roleName: 'Wise Old Man',
      id: '45',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You know all Special Villagers but will die after 2 days.',
    },
    {
      roleName: 'Warlock (new Witch)',
      id: '46',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '1',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '1',
      gameSpeed: 'Neutral',
      moderatorText: 'You have a potion to bring the dead back to life.',
    },
    {
      roleName: 'Leprechaun',
      id: '47',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '1',
      gameSpeed: 'Neutral',
      moderatorText:
        'You may redirect the Werewolves’ target one player to the right or left.',
    },
    {
      roleName: 'Seer',
      id: '48',
      roleType: 'specialVillager',
      set: 'Extreme',
      infoValue: '2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Search for Werewolves at night.',
    },
  ],
  specialWerewolf: [
    {
      roleName: 'Wolf Mama (new Mystery Wolf)',
      id: '49',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '-2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'First two nights add another Lycan.',
    },
    {
      roleName: 'Wolf Man',
      id: '50',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'You are invisible to Seer.',
    },
    {
      roleName: 'Guzzle Wolf (apprentice Big Bad Wolf)',
      id: '51',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText: 'If the village doesn’t kill you will take an extra kill.',
    },
    {
      roleName: 'Hunter Wolf',
      id: '53',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Easy',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'Wake with the wolves. If you are eliminated you may eliminate any other player.',
    },
    {
      roleName: 'Kamikaze Wolf',
      id: '54',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'If the Seer views you both you and the Seer are eliminated.',
    },
    {
      roleName: 'Oracle Wolf (alt)',
      id: '55',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Wake with the wolves. Each night after a werewolf is killed you wake again and learn the exact role of one player.',
    },
    {
      roleName: 'Pet Wolf',
      id: '56',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You were once the pet of someone in the village. If you die they will remember and die of heartbreak.',
    },
    {
      roleName: 'Prairie Wolf (Jacole)',
      id: '57',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Wake with the wolves. On set-up and every time a Werewolf dies choose a player and learn if that player has an Aura.',
    },
    {
      roleName: 'Sorcerer Wolf (new Dreamwolf)',
      id: '58',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Slower',
      moderatorText:
        'Don’t wake with werewolves until they attack you. Until then look for the Seer.',
    },
    {
      roleName: 'Wolf Cub',
      id: '59',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'If you die the Werewolves will go on a rampage and take an extra kill.',
    },
    {
      roleName: 'Wolverine',
      id: '60',
      roleType: 'specialWerewolf',
      set: 'Extreme',
      infoValue: '2',
      isIndependant: '1',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'When you are closest to the kill the village hears the sound of slashing metallic claws',
    },
  ],
  werewolfSupport: [
    {
      roleName: 'Apprentice Illusionist',
      id: '61',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'If the Seer sees you their next view will be opposite',
    },
    {
      roleName: 'Reviler',
      id: '62',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Faster',
      moderatorText:
        'You may gamble that you can find a Special Villager. If you are right they die. If you are wrong you die.',
    },
    {
      roleName: 'Spawn',
      id: '63',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '-1',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Slower',
      moderatorText:
        'If you outlive all the Werewolves you become the last Werewolf.',
    },
    {
      roleName: 'Count Lycanthrope (new Count)',
      id: '64',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'know how many Werewolves and Seer in each half of the village.',
    },
    {
      roleName: 'Dark Empath',
      id: '65',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Easy',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Each night learn if the Seer is adjacent to a wolf.',
    },
    {
      roleName: 'Den Mother',
      id: '66',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'You know when the Seer finds a Werewolf and when Seer is dead',
    },
    {
      roleName: 'Devotee (new Minion)',
      id: '67',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Each night learn about one new Werewolf.',
    },
    {
      roleName: 'The Mummy (alt)',
      id: '68',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Each night pick a player to be hypnotized. That player will vote the way you do.',
    },
    {
      roleName: 'Sorceress',
      id: '69',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText: 'Search for the Seer at night.',
    },
    {
      roleName: 'Spy',
      id: '70',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '1',
      moderatorDifficulty: 'Medium',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Each night learn who the Seer viewed then search for Werewolves',
    },
    {
      roleName: 'The Mummy (alt)',
      id: '71',
      roleType: 'werewolfSupport',
      set: 'Extreme',
      infoValue: '0',
      isIndependant: '0',
      requireSeer: '0',
      moderatorDifficulty: 'Very Hard',
      isProtector: '0',
      gameSpeed: 'Neutral',
      moderatorText:
        'Each night pick a player to be hypnotized. That player will vote the way you do.',
    },
  ],
};
module.exports = roleList;
